version: "3"
services:
    app:
      build:
        context: .
      working_dir: /app
      restart: unless-stopped
      volumes:
        - ./:/app
      ports: 
        - 8090:8090
    postgres:
      image: postgres
      container_name: postgres
      ports:
        - 5432:5432
      env_file:
        - ./app.env
      environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
        - postgres:/var/lib/postgresql/data
volumes:
  postgres:
